config/routes.rb
Rails.application.routes.draw do

  get 'my_organizations/index'

  get 'my_organizations_controller/index'

  get "/" => redirect("/ru/")
  
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    root to: 'home#index'
    get :greeting, to: 'home#greeting'
    resources :contacts, only: [:index, :create, :destroy]
    resources :posts, only: [:index, :show]
    resources :interviews, only: [:index, :show]
    resources :pages, only: [:index, :show]
    resources :menu_items, only: [:show]
    resources :votes, only: :index do
      post :vote
    end
    resources :user_options, only: :create
    resources :organizations, only: [:index, :edit, :show, :update]
    resources :my_posts, only: [:index, :new, :create]
    resources :my_organizations, only: :index

    namespace :admin do
      root 'dashboard#index'

      resources :users, except: :show
      resources :organizations, except: :show
      resources :pages, except: :show
      # resources :presentations, except: :show
      resources :posts, except: :show
      resources :interviews, except: :show
      resources :activity_types, except: :show
      resources :page_fragments, only: [:index, :edit, :update]
      resources :votes, except: :show
      resources :groups, except: :show
      resources :slides, except: :show
      resources :mailings, except: :show
      resources :contacts, only: [:index, :show]
      resource :settings, except: [:new, :create, :destroy]

      resources :menu_items, except: [:show] do
        member { put :move }
      end

      resources :imperavi_pictures, only: [:index, :create, :show, :destroy]
      resources :imperavi_attachments, only: [:index, :create, :destroy]
    end

    resources :messages, only: [:edit, :create, :update, :destroy]

    resources :topics, path: '/forum' do
      member do
        post :archive
        post :unarchive
      end
      collection { get :archived }
    end

    devise_for(:users,
      controllers: {
        sessions: 'sessions',
        registrations: 'registrations',
        passwords: 'passwords'
      }
    )

    devise_scope :user do
      get 'register', to: 'registrations#new'
      get 'profile', to: 'registrations#edit'
      get 'login', to: 'sessions#new'
    end
  end

  match '/404' => 'errors#error404', via: [ :get, :post, :put, :patch, :delete ]
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  attr_accessor :text
  attr_accessor :group_ids

  TOPIC_OPEN = 'open'
  TOPIC_PRIVATE = 'private'
  TOPIC_TYPES = [TOPIC_OPEN, TOPIC_PRIVATE]

  belongs_to :user
  has_many :messages, autosave: true
  has_and_belongs_to_many :users

  validates :title, :user, :text, presence: true
  validates :topic_type, inclusion: TOPIC_TYPES

  before_save :pluck_users

  after_initialize :build_first_message, if: :new_record?
  after_save :change_first_message, on: :update

  accepts_nested_attributes_for :messages
  accepts_nested_attributes_for :users

  scope :by_user, -> (id) { where("topic_type='open' OR (topic_type='private' AND user_id = ?)", id) }
  scope :archived, -> { where is_archieved: true }
  scope :not_archived, -> { where is_archieved: false }
  scope :by_last_message_at, -> { order last_message_at: :desc }

  def initialize(args={})
    super
    topic_type ||= TOPIC_PRIVATE
  end

  def text
    @text || self.messages.first.try(:text)
  end

  def archive!
    self.update is_archieved: true
  end

  def unarchive!
    self.update is_archieved: false
  end

  private

  def build_first_message
    self.messages.build topic: self, user: self.user, text: self.text
  end

  def change_first_message
    self.messages.first.update text: self.text
  end

  def pluck_users
    return true if self.group_ids.nil?
    arr = self.user_ids
    group_ids = self.group_ids.delete_if{|i| i.blank? }
    Group.find(group_ids).each do |group|
      arr += group.users.active.ids
    end
    self.user_ids = arr.uniq
    self.group_ids = nil
    true
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::Dirty
  # include ImageUploading
  dragonfly_accessor :image do
    default 'public/images/profile.png'
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable

  ROLES = [:admin, :moderator, :normal, :guest]

  attr_accessor :organization_not_in_list

  validates :role, inclusion: ROLES.map(&:to_s)
  validates :first_name, :middle_name, :last_name, :post, presence: true
  validates :organizations, presence: true, if: Proc.new{
    |u| (!u.organization_not_in_list? && u.outer_organization.blank? && !role?(:admin)) 
  }
  validates :outer_organization, presence: true, if: Proc.new{ |u| (u.organization_not_in_list? && !role?(:admin)) }

  before_validation :setup_role
  after_create :send_approval_request, 
               :send_registration_info,
               if: Proc.new { |user| user.role?(:normal) }
  after_update :check_approval,
               if: Proc.new { |user| user.role?(:normal) } 

  after_commit :notify_admin_on_registration_info, on: [:create],
               if: Proc.new { |user| user.role?(:normal) }

  has_and_belongs_to_many :organizations

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  has_many :user_options
  scope :active, -> { where(approved: true) }

  # alias_method :img, :image
  # def image
  #   img || Dragonfly.app.fetch_file(File.join(Rails.root, 'app', 'assets', 'images', 'profile.png'))
  # end

  def setup_role
    unless role.present?
      if organization_not_in_list? && outer_organization.present?
        self.role = :guest
      elsif organization.present?
        self.role = :normal
      end
    end
  end

  def role?(role)
    return false unless ROLES.include?(role.to_sym)
    role.to_sym == self.role.try(:to_sym)
  end

  def active_for_authentication? 
    super && (role?(:guest) && approved?) ||  
    (role?(:normal) && approved?) || role?(:admin) || role?(:moderator)
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  def send_approval_request
    UserMailer.approval_request(self).deliver_now
  end

  def send_registration_info
    UserMailer.registration_info(self).deliver_now
  end

  def notify_admin_on_registration_info
    admins = User.where id: (Settings.first.user_notification_user_ids || [])
    admins.each do |admin|
      UserMailer.delay.notify_admin_on_registration_info(admin, self)
    end
  end

  def check_approval
    if approved_changed?
      UserMailer.account_approved(self).deliver_now
    end
  end

  def full_name
    name = [last_name, first_name, middle_name].join(" ")
    unless name.blank?
      name
    else
      email
    end
  end

  def short_name
    m = "#{middle_name[0]}." if middle_name
    name = [first_name, m, last_name].compact.join(" ")
  end

  def to_s
    full_name
  end

  # def admin
  #   role?(:admin)
  # end

  # def manager
  #   role?(:manager)
  # end

  def organization_not_in_list?
    organization_not_in_list.to_i.zero? ? false : true
  end

  def voted?(vote)
    organization_ids = self.organizations.map {|organization| organization.id}
    voted_ids = self.voted_options(vote).map {|option| option.organization_id}
    organization_ids & voted_ids == organization_ids
  end

  def voted_options(vote)
    UserOption.where(organization_id: self.organizations.map {|organization| organization.id}, vote_id: vote.id)
  end

  def organization_options
    organizations = []
    self.organizations.each do |organization|
      organizations.push({
        :id => organization.id,
        :name => organization.name
      })
    end
    organizations
  end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  layout 'application'

  before_action :authenticate_user!
  before_action :authorize_user!

  before_action :set_topic, only: [:show, :edit, :update, :destroy, :archive, :unarchive]
  before_action :set_messages, only: [:show, :edit]
  before_action :set_new_message, only: [:show, :edit]

  def index
    @topics = Topic.accessible_by(current_ability).not_archived.by_last_message_at.page(params[:page]).per(10)
  end

  def archived
    @topics = Topic.accessible_by(current_ability).archived.by_last_message_at.page(params[:page]).per(10)
    render template: "topics/index"
  end

  def show
    build_breadcrumbs
  end

  def new
    @topic = Topic.new
    @groups = Group.accessible_by(current_ability)
    @breadcrumbs = [root_breadcrumb] + [{ name: I18n.t('views.topics.index.title'), url: topics_path }, { name: t('views.topics.new.title') }]
  end

  def edit
    @groups = Group.accessible_by(current_ability)
    @breadcrumbs = [root_breadcrumb] + [{ name: I18n.t('views.topics.index.title'), url: topics_path }, { name: t('views.topics.edit.title') }]
  end

  def create
    @topic = Topic.new(topic_params.merge(user: current_user))
    authorize! :create, @topic
    @groups = Group.accessible_by(current_ability)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: t('views.topics.flash.successfully_created') }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :update, @topic
    @groups = Group.accessible_by(current_ability)
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: t('views.topics.flash.successfully_updated') }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @topic
    @topic.destroy
    
    respond_to do |format|
      format.html { redirect_to topics_url, notice: t('views.topics.flash.successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  def archive
    authorize! :update, @topic
    respond_to do |format|
      if @topic.archive!
        format.html { redirect_to topics_url, notice: t('views.topics.flash.archived') }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def unarchive
    authorize! :update, @topic
    respond_to do |format|
      if @topic.unarchive!
        format.html { redirect_to topics_url, notice: t('views.topics.flash.unarchived') }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  protected

  def authorize_user!
    # raise CanCan::AccessDenied if current_user.nil? || current_user.role?(:client) || current_user.role?(:normal)
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def set_messages
    @messages = Message.where(topic: @topic)
  end

  def set_new_message
    @message = Message.new(topic: @topic, user: current_user)
  end

  def topic_params
    params.require(:topic).permit(:title, :is_archieved, :topic_type, :user_id, :text, group_ids: [], user_ids: [])
  end

  def message_params
    params.require(:message).permit(:text)
  end

  def build_breadcrumbs
    @breadcrumbs = [root_breadcrumb]
    @breadcrumbs += [{ name: I18n.t('views.topics.index.title'), url: topics_path }]

    @breadcrumbs.push name: @topic.title

    @breadcrumbs
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topic_type_icon(topic_type)
    res = case topic_type
      when 'open'
        content_tag :div, class: "icon-wrapper icon-#{topic_type}", title: t("helpers.topics.type.#{topic_type}") do
          content_tag :i, '', class: 'fa fa-icon fa-eye'
        end
      when 'private'
        content_tag :div, class: "icon-wrapper icon-#{topic_type}", title: t("helpers.topics.type.#{topic_type}") do
          content_tag :i, '', class: 'fa fa-icon fa-eye-slash'
        end
      else ''
    end
  end
end

app/views/topics/_form.html.slim
.basic-form
  = simple_nested_form_for @topic, html: { class: "form-horizontal" } do |f|
    = error_explanation(@topic, filter: [:'messages.text'])
    .form-inputs
      = f.input :title
      - if [:normal, :guest].include? current_user.role.to_sym 
        = f.input :topic_type, as: :hidden, input_html: { value: Topic::TOPIC_PRIVATE}   
      - else    
        = f.input :topic_type, collection: [[t('activerecord.attributes.topic.topic_types.open'), Topic::TOPIC_OPEN], [t('activerecord.attributes.topic.topic_types.private'), Topic::TOPIC_PRIVATE]], 
          include_blank: false, input_html: { class: 'select2-input' }
      = f.input :text, as: :text, input_html: { class: 'imperavi-input' }

      - unless @topic.topic_type == Topic::TOPIC_OPEN
        - if current_user.present? && ['admin', 'moderator'].include?(current_user.role)
          = f.input :group_ids, as: :select, collection: @groups.map{|group| [group.title, group.id] }, input_html: {class: 'select2-input', multiple: true}

        = f.association :users, collection: User.active, input_html: {class: 'select2-input'}

    .form-actions
      = f.submit

app/views/topics/_message_form.html.slim
.basic-form
  .form-title
    h4= t('views.topics.show.add_message')
  = simple_form_for @message do |f|
    = error_explanation(@message)

    = f.hidden_field :topic_id, value: @topic.id

    .form-inputs
      = f.input :text, as: :text, input_html: { class: 'imperavi-input' }

    .form-actions
      = f.submit t('helpers.send')

app/views/topics/_messages.html.slim
.messages
  - @topic.messages.each do |m|
    .message class="#{cycle('even', 'odd')}"
      .header
        - if m.user.image
          .avatar = image_tag m.user.image.thumb('40x40#').url
        / - else
        /   .avatar = image_tag Dragonfly.app.fetch_file('/app/assets/images/profile.png')
        /   .avatar = image_tag Dragonfly.app.fetch_file(image_url('profile.png')).thumb('40x40#').url
        .author = m.user.full_name
        .publish-date = l(m.created_at, format: :publish_date)
        .clearfix
      .content == m.text
      .actions
        .form_group
        - if can? :update, m
          = link_to t('helpers.edit'), edit_message_path(m.id),
            class: 'btn primary'
        - if can? :destroy, m
          = link_to t('helpers.delete'), message_path(m.id), 
            data: { confirm: 'Вы уверены?' }, method: :delete,
            class: 'btn danger pull-right'

app/views/topics/edit.html.slim
.-container.inner.forum
  .-row
    .-col12
      = render_frontend_breadcrumbs

  .-row
    .-col12
      h1.base-title = t 'views.topics.edit.title'

  .-row
    .-col12
      == render 'form'

  .-row
    .-col12
      .base-buttons
        = link_to t("helpers.cancel"), @topic, class: 'btn default'

        - unless @topic.is_archieved
          = link_to t("helpers.archive"), archive_topic_path(@topic), method: :post, class: 'btn warning'

        = link_to t("helpers.link_to.back"), topics_path, class: 'btn primary'

app/views/topics/index.html.slim
.-container.inner.forum
  .-row
    .-col12
      h1.base-title = t 'views.topics.index.title'

  .-row
    .-col12
      table
        thead
          tr
            th.title = t('views.topics.index.labels.title')
            th.author = t('views.topics.index.labels.author')
            th.topic-type = t('views.topics.index.labels.topic_type')
            th.messages-count 
              = fa_icon "comments-o", title: t('views.topics.index.labels.messages_count')
            th.last-message = t('views.topics.index.labels.last_message')
            th.topic-actions

        tbody
          - @topics.each do |topic|
            tr class="#{cycle('even', 'odd')}"
              td.title = link_to topic.title, topic_path(topic)
              td.author = User.find(topic.user_id).short_name
              td.topic-type = topic_type_icon(topic.topic_type)
              td.messages-count = topic.messages.count
              td.last-message  
                - if topic.messages.last.present?
                  = l(topic.messages.last.created_at, format: :publish_date)
              td.topic-actions 
                - if can? :update, topic
                  = link_to edit_topic_path(topic), class: 'btn success', title: t('helpers.edit') do
                    = fa_icon 'pencil-square'
                  - if topic.is_archieved
                    = link_to unarchive_topic_path(topic), method: :post, class: 'btn warning', title: t('helpers.unarchive') do
                      = fa_icon 'mail-reply-all' 
                  - else
                    = link_to archive_topic_path(topic), method: :post, class: 'btn warning', title: t('helpers.archive') do
                      = fa_icon 'archive'
                - if can? :destroy, topic
                  = link_to topic, data: { confirm: 'Вы уверены?' }, method: :delete, class: 'btn danger', title: t('helpers.delete') do
                    = fa_icon 'trash'
    .-col12
      .base-pagination
        = paginate @topics

  .-row
    .-col12
      .base-buttons
        - if params[:action] != 'archived'
          = link_to t('views.topics.index.labels.archived'), archived_topics_path, class: 'btn primary'
        - else
          = link_to t('views.topics.index.labels.themes'), topics_path, class: 'btn default'
        = link_to t('views.topics.index.labels.new_theme'), new_topic_path, class: 'btn success'

app/views/topics/new.html.slim
.-container.inner
  .-row
    .-col12
      = render_frontend_breadcrumbs

  .-row
    .-col12
      h1.base-title = t("views.topics.new.title")

  .-row
    .-col12
      == render 'form'

  .-row
    .-col12
      .base-buttons
        = link_to t('helpers.link_to.back'), topics_path, class: 'btn default'

app/views/topics/show.html.slim
.-container.inner.forum
  .-row
    .-col12
      = render_frontend_breadcrumbs

  .-row
    .-col12
      h1.base-title 
        = @topic.title + (@topic.is_archieved ? " (#{ t('views.topics.show.archived') })" : '')
      .topic-title-hint
        - if @topic.topic_type == 'open'
          = t('views.topics.show.type.open')
        - elsif @topic.topic_type == 'private'
          = t('views.topics.show.type.private')
      .topic-author
        .label = t('views.topics.show.author')
        .value = @topic.user.full_name

  == render 'topics/messages'

  - unless @topic.is_archieved
    == render 'topics/message_form'

  .-row
    .-col12
      .social_share
        h4= t('helpers.social_share')
        = render partial: 'shared/shared_links', locals: {title: @topic.title}
    .-col12
      .base-buttons
        - if can? :update, @topic
          - if @topic.is_archieved
            = link_to t('helpers.unarchive'), unarchive_topic_path(@topic), method: :post, class: 'btn warning'
          - else
            = link_to t('helpers.archive'), archive_topic_path(@topic), method: :post, class: 'btn warning'
          = link_to t('helpers.edit'), edit_topic_path(@topic), class: 'btn success'
        = link_to t("helpers.link_to.back"), topics_path, class: 'btn primary'