config/routes.rb
Rails.application.routes.draw do

  get 'my_organizations/index'

  get 'my_organizations_controller/index'

  get "/" => redirect("/ru/")
  
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    root to: 'home#index'
    get :greeting, to: 'home#greeting'
    resources :contacts, only: [:index, :create, :destroy]
    resources :posts, only: [:index, :show]
    resources :interviews, only: [:index, :show]
    resources :pages, only: [:index, :show]
    resources :menu_items, only: [:show]
    resources :votes, only: :index do
      post :vote
    end
    resources :user_options, only: :create
    resources :organizations, only: [:index, :edit, :show, :update]
    resources :my_posts, only: [:index, :new, :create]
    resources :my_organizations, only: :index

    namespace :admin do
      root 'dashboard#index'

      resources :users, except: :show
      resources :organizations, except: :show
      resources :pages, except: :show
      # resources :presentations, except: :show
      resources :posts, except: :show
      resources :interviews, except: :show
      resources :activity_types, except: :show
      resources :page_fragments, only: [:index, :edit, :update]
      resources :votes, except: :show
      resources :groups, except: :show
      resources :slides, except: :show
      resources :mailings, except: :show
      resources :contacts, only: [:index, :show]
      resource :settings, except: [:new, :create, :destroy]

      resources :menu_items, except: [:show] do
        member { put :move }
      end

      resources :imperavi_pictures, only: [:index, :create, :show, :destroy]
      resources :imperavi_attachments, only: [:index, :create, :destroy]
    end

    resources :messages, only: [:edit, :create, :update, :destroy]

    resources :topics, path: '/forum' do
      member do
        post :archive
        post :unarchive
      end
      collection { get :archived }
    end

    devise_for(:users,
      controllers: {
        sessions: 'sessions',
        registrations: 'registrations',
        passwords: 'passwords'
      }
    )

    devise_scope :user do
      get 'register', to: 'registrations#new'
      get 'profile', to: 'registrations#edit'
      get 'login', to: 'sessions#new'
    end
  end

  match '/404' => 'errors#error404', via: [ :get, :post, :put, :patch, :delete ]
end

app/views/shared/_footer.slim
.footer-inner.-container 
  .-container
    .-row
      .-col3.left
        = link_to root_path, class: 'link-to-root' do
          = image_tag "logo-footer-#{I18n.locale}.png"
      .-col5.-offset1.middle
        .section
          - items = MenuItem.get('footer').try(:children, { published:true })
          - items.each do |item|
            - if item.children.present?
              .column
                .title = item.title
                ul
                  - item.children.each do |item|
                    li = link_to item.title, menu_item_smart_url(item)
      .-col2.right
        .section
          .column
            .title = t('helpers.contacts')
            .sub
              == @pf_footer_contacts.try(:content)

              - if [@settings.ig_url,@settings.vk_url,@settings.fb_url,@settings.ln_url].any? {|url| url.present?}
                .social-media
                  p = t("views.main.footer.social")
                  .wrap
                    - if @settings.ig_url.present?
                      = link_to @settings.ig_url do
                        .icon.ig
                    - if @settings.vk_url.present?
                      = link_to @settings.vk_url do
                        .icon.vk
                    - if @settings.fb_url.present?
                      = link_to @settings.fb_url do
                        .icon.fb
                    - if @settings.ln_url.present?
                      = link_to @settings.ln_url do
                        .icon.ln

  .-container
    .-row
      .-col12
        .bottom-line = t("views.main.footer.bottom")

app/views/shared/_gallery.slim
.organization-gallery-wrapper
  .fancybox.gallery-slider
    - @resource.pictures.each do |picture|
      .slide
        .image
          = link_to picture.file.url, rel: "gallery-#{picture.target_type}-#{picture.target_id}",
                  class: 'fancybox-slide', data: { fancybox_title: "#{picture.description} " } do
            = image_tag picture.file.url

app/views/shared/_header.slim
.header-inner
  .header-top.-container
    = link_to root_path, class: 'link-to-root' do
      = image_tag "logo-#{I18n.locale}.png", class: 'logo-default'
      = image_tag "logo-small-#{I18n.locale}.png", class: 'logo-small'
    
    .contacts
      .item.phone 
        .value = @settings.try(:contact_phone_number)
      .item.email
        .value = mail_to @settings.try(:contact_email)
    
    = locales_selector
    
    = font_size_selector

    - if [@settings.ig_url,@settings.vk_url,@settings.fb_url,@settings.ln_url].any? {|url| url.present?}
      .social-media
        .label = t("views.main.header.social")
        - if @settings.ig_url.present?
          = link_to @settings.ig_url do
            .icon.ig
        - if @settings.vk_url.present?
          = link_to @settings.vk_url do
            .icon.vk
        - if @settings.fb_url.present?
          = link_to @settings.fb_url do
            .icon.fb
        - if @settings.ln_url.present?
          = link_to @settings.ln_url do
            .icon.ln

  .mainmenu.-container
    .menu-btn = fa_icon 'bars'
    ul.top-ul
      - main_menu_items = MenuItem.get('main').try(:children, { published:true })
      - if main_menu_items
        - if !(session[:font_size] == 'small' || session[:font_size].nil?)
          li
            = link_to '#', class: 'burger menu-item' do
              span= t('helpers.menu')
            .submenu
              ul.nested-ul
                - main_menu_items.each do |item|
                  - if item.children.any?
                    li
                      = link_to '#', class: 'menu-item' do
                        span= item.title
                        .arrow
                      .nested-submenu
                        - item.children.each do |child|
                          - child_url = menu_item_smart_url child
                          = link_to child.title, child_url
                  - else
                    - url = menu_item_smart_url(item)
                    li= link_to item.title, url, class: 'menu-item'

        - main_menu_items.each do |item|
          - url = menu_item_smart_url item
          li
            = link_to url, class: 'menu-item' do
              span = item.title
              - if item.children.any?
                .arrow
            - if item.children.any?
              .submenu
                - item.children.each do |child|
                  - child_url = menu_item_smart_url child
                  = link_to child.title, child_url

    .dashboard-link
      ul.top-ul
        - if current_user.present?
          li
            = link_to '#', class: 'main' do
              span= t('application.dashboard.cabinet')
              .arrow
            .submenu
              - if can? :update, current_user 
                = link_to t('application.dashboard.my_profile'), profile_path
              - if (current_user.organizations.length==1) && can?(:update, current_user.organizations.first)
                = link_to t('application.dashboard.my_organization'), organization_path(current_user.organizations[0])
              - if (current_user.organizations.length>1)
                = link_to t('application.dashboard.my_organization'), my_organizations_path
              - if can? :read, Topic
                = link_to t('application.dashboard.forum'), topics_path
              = link_to t('application.dashboard.surveys'), votes_path
              - if ['normal', 'guest'].include? current_user.role
                = link_to t('application.dashboard.suggest_adv'), my_posts_path
              = link_to t('application.dashboard.sign_out'), destroy_user_session_path, method: :delete
        - else
          li
            = link_to login_path, class: 'main' do
              span= t('application.dashboard.cabinet')

app/views/shared/_main_slider.slim
.main-slider
  - @slides.each do |slide|
    .slide style="background-image: url(#{slide.image.thumb("1440x380").url}); background-size: cover; background-repeat: no-repeat;"
      .inner
        .wrapper
          - unless slide.title.blank?
            .title 
              = slide.title
          - unless slide.subtitle.blank?
            .subtitle 
              = slide.subtitle
          / .button
          /   = link_to t('helpers.become_resident'), contacts_path

app/views/shared/_residents_slider.slim
.residents-slider-wrapper
  .title = t('views.main.residents.title')
  .subtitle = t('views.main.residents.subtitle')
  .residents-slider
    - @residents.each do |slide|
      = link_to slide, class: 'slide' do
        .inner
          .image
            = image_tag slide.logo ? slide.logo.url : 'default_logo.jpg'
          .title = slide.name

app/views/shared/_shared_links.slim
- content_for :head do
  meta property="og:title" content="#{title if local_assigns.has_key?(:title)}"


script(src="https://yastatic.net/share2/share.js" async="async")
.ya-share2 (
  data-services="facebook,twitter,vkontakte,linkedin"
  data-counter="data-counter"
  data-title="#{title if local_assigns.has_key?(:title)}"
)