config/routes.rb
Rails.application.routes.draw do

  get 'my_organizations/index'

  get 'my_organizations_controller/index'

  get "/" => redirect("/ru/")
  
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    root to: 'home#index'
    get :greeting, to: 'home#greeting'
    resources :contacts, only: [:index, :create, :destroy]
    resources :posts, only: [:index, :show]
    resources :interviews, only: [:index, :show]
    resources :pages, only: [:index, :show]
    resources :menu_items, only: [:show]
    resources :votes, only: :index do
      post :vote
    end
    resources :user_options, only: :create
    resources :organizations, only: [:index, :edit, :show, :update]
    resources :my_posts, only: [:index, :new, :create]
    resources :my_organizations, only: :index

    namespace :admin do
      root 'dashboard#index'

      resources :users, except: :show
      resources :organizations, except: :show
      resources :pages, except: :show
      # resources :presentations, except: :show
      resources :posts, except: :show
      resources :interviews, except: :show
      resources :activity_types, except: :show
      resources :page_fragments, only: [:index, :edit, :update]
      resources :votes, except: :show
      resources :groups, except: :show
      resources :slides, except: :show
      resources :mailings, except: :show
      resources :contacts, only: [:index, :show]
      resource :settings, except: [:new, :create, :destroy]

      resources :menu_items, except: [:show] do
        member { put :move }
      end

      resources :imperavi_pictures, only: [:index, :create, :show, :destroy]
      resources :imperavi_attachments, only: [:index, :create, :destroy]
    end

    resources :messages, only: [:edit, :create, :update, :destroy]

    resources :topics, path: '/forum' do
      member do
        post :archive
        post :unarchive
      end
      collection { get :archived }
    end

    devise_for(:users,
      controllers: {
        sessions: 'sessions',
        registrations: 'registrations',
        passwords: 'passwords'
      }
    )

    devise_scope :user do
      get 'register', to: 'registrations#new'
      get 'profile', to: 'registrations#edit'
      get 'login', to: 'sessions#new'
    end
  end

  match '/404' => 'errors#error404', via: [ :get, :post, :put, :patch, :delete ]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'

  def index
    @vote = Vote.accessible_by(current_ability).published.where(closed: false).order(:date_start).try(:first) if current_user.present?
    if @vote.blank?
      @posts = Post.published.desc.limit(4)
    else
      @posts = Post.published.desc.limit(2)
    end
    @interview = Interview.published.desc.limit(1).first
    @pf_main_about = PageFragment.key("main_page_about").first
    @slides = Slide.published.desc
    @residents = Organization.in_slider.limit(50)
  end

  def greeting
    @breadcrumbs = [root_breadcrumb] + [{ name: @settings.greeting_title}]
  end
end

app/views/home/greeting.slim
.-container.inner.greeting
  .-row
    .-col12
      = render_frontend_breadcrumbs

  .-row.content-with-margins
    .-col12
      h1.base-title== @settings.greeting_title
      h3.short_description== @settings.greeting_short_description
      .card.-row
        - if @settings.greeting_image.present?
          .-col6
            = image_tag(@settings.greeting_image.url)
        .-col6
          == @settings.greeting_paragraph_1
      .-row
        .-col9.-offset3.content
          == @settings.greeting_paragraph_2
        .-col9.-offset3
          .social_share
            h4= t('helpers.social_share')
            = render partial: 'shared/shared_links', locals: {title: @settings.greeting_title}
  .clearfix

app/views/home/index.slim
.main-page
  == render 'shared/main_slider' if @slides.present?

  .-container
    .-row
      - if @vote.present?
        .-col8
          .posts-main-page
            .label
              span = t('views.main.posts.title')

            = render partial: 'posts/list', collection: @posts, as: :item

        .-col4
          .votes-main-page
            .label
              span = t('views.main.votes.title')
            = link_to votes_path(expand: @vote.id), class: "vote-static-container" do
              = render 'votes/vote_form', vote: @vote

      - else
        .posts-main-page
          .label
              span = t('views.main.posts.title')
          .-col6
            = render partial: 'posts/list', collection: @posts[0..1], as: :item
          .-col6
            = render partial: 'posts/list', collection: @posts[2..3], as: :item

  - if @interview.present?
    .-container
      .-row
        .-col12
          .interview-main-page
            = link_to interview_path(@interview), class: 'item' do 
              .image = image_tag @interview.image.thumb('190x160#').url
              .content
                .label
                  span = t('views.main.interviews.title')
                .title = @interview.title
                .intro == @interview.intro
                .more = t('helpers.read_more')

  .-container.page-fragment.main-about
    .-row
      .-col5.-offset1
        .main-about-content
          == @pf_main_about.content
      .-col6
        = image_tag("pf-about-cluster-#{I18n.locale}.png", width: '100%', height: '100%')

  == render 'shared/residents_slider' if @residents.present?
  