config/routes.rb
Rails.application.routes.draw do

  get 'my_organizations/index'

  get 'my_organizations_controller/index'

  get "/" => redirect("/ru/")
  
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    root to: 'home#index'
    get :greeting, to: 'home#greeting'
    resources :contacts, only: [:index, :create, :destroy]
    resources :posts, only: [:index, :show]
    resources :interviews, only: [:index, :show]
    resources :pages, only: [:index, :show]
    resources :menu_items, only: [:show]
    resources :votes, only: :index do
      post :vote
    end
    resources :user_options, only: :create
    resources :organizations, only: [:index, :edit, :show, :update]
    resources :my_posts, only: [:index, :new, :create]
    resources :my_organizations, only: :index

    namespace :admin do
      root 'dashboard#index'

      resources :users, except: :show
      resources :organizations, except: :show
      resources :pages, except: :show
      # resources :presentations, except: :show
      resources :posts, except: :show
      resources :interviews, except: :show
      resources :activity_types, except: :show
      resources :page_fragments, only: [:index, :edit, :update]
      resources :votes, except: :show
      resources :groups, except: :show
      resources :slides, except: :show
      resources :mailings, except: :show
      resources :contacts, only: [:index, :show]
      resource :settings, except: [:new, :create, :destroy]

      resources :menu_items, except: [:show] do
        member { put :move }
      end

      resources :imperavi_pictures, only: [:index, :create, :show, :destroy]
      resources :imperavi_attachments, only: [:index, :create, :destroy]
    end

    resources :messages, only: [:edit, :create, :update, :destroy]

    resources :topics, path: '/forum' do
      member do
        post :archive
        post :unarchive
      end
      collection { get :archived }
    end

    devise_for(:users,
      controllers: {
        sessions: 'sessions',
        registrations: 'registrations',
        passwords: 'passwords'
      }
    )

    devise_scope :user do
      get 'register', to: 'registrations#new'
      get 'profile', to: 'registrations#edit'
      get 'login', to: 'sessions#new'
    end
  end

  match '/404' => 'errors#error404', via: [ :get, :post, :put, :patch, :delete ]
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  include HasPictures
  validates :name, presence: true

  has_many :organization_activity_types, dependent: :destroy
  has_many :activity_types, through: :organization_activity_types
  has_and_belongs_to_many :users
  has_many :organization_attachments, dependent: :destroy
  accepts_nested_attributes_for :organization_attachments, :pictures, allow_destroy: true
  accepts_nested_attributes_for :activity_types

  multilang :name, :chief_name, :competence, :capabilities,
            :offers, :interests, :contacts, :address

  dragonfly_accessor :logo

  geojson_accessor :coordinates

  scope :in_slider, -> { where(in_slider: true) }
  scope :by_query, -> query { where("name ->> :key ILIKE :value", key: I18n.locale.to_s, value: "%#{query}%") }

  acts_as_url :name, limit: 64, truncate_words: false

  def self.search search_string
    where("name ->> :key ILIKE :value", key: I18n.locale.to_s, value: "%#{search_string}%")
  end

  def to_param
    url
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::AdminController
  load_and_authorize_resource instance_name: :resource, find_by: :url

  has_scope :by_query, as: :query

  def index
    @collection = apply_scopes(Organization).page(params[:page])
    respond_with @collection
  end

  def new
    @resource = Organization.new
  end

  def create
    @resource = Organization.new(resource_params)
    @resource.save
    respond_with(:admin, @resource)
  end

  def update
    @resource.update(resource_params)
    respond_with(:admin, @resource)
  end

  def destroy
    @resource.destroy
    respond_with(:admin, @resource)
  end

  def attachments_permit
    {organization_attachments_attributes: [:id, :_destroy, :remove_organization_attachment, 
    :organization_attachment_cache, :organization_id, :description] + fp(:file)}
  end

  def resource_params
    allowed = [
      lp(:name), lp(:chief_name), lp(:competence),
      lp(:capabilities), lp(:offers), lp(:interests),
      lp(:contacts), lp(:address), :website,
      :coordinates_geojson, :in_slider, attachments_permit,
      image_permit(:logo), gallery_permit,
      activity_type_ids: []
    ]

    params.require(:organization).permit(*allowed)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  load_and_authorize_resource instance_name: :resource, find_by: :url

  def index
    @collection = Organization.search(params[:search]).order("name->'"+I18n.locale.to_s+"' ASC").page(params[:page]).per(12)
    @breadcrumbs = [root_breadcrumb] + [{ name: I18n.t('views.organizations.index.title') }]
    if request.xhr?
      render partial: 'search_results'
    end
  end

  def show
    build_breadcrumbs
  end

  def edit
    build_breadcrumbs
  end

  def update
    if @resource.update(organization_params)
      redirect_to @resource, notice:I18n.t('views.organizations.flash.successfully_updated')
    else
      render :edit
    end
  end

  private

  def build_breadcrumbs
    @breadcrumbs = [root_breadcrumb]
    @breadcrumbs += [{ name: I18n.t('views.main.residents.title'), url: organizations_path }]

    @breadcrumbs.push name: @resource.name

    @breadcrumbs
  end

  def attachments_permit
    {organization_attachments_attributes: [:id, :_destroy, :remove_organization_attachment, 
    :organization_attachment_cache, :organization_id, :description] + fp(:file)}
  end

  def organization_params
    params.require(:organization).permit(attachments_permit)
  end
end

app/views/admin/organizations/_attachments.slim
.form-group.row.organization-attachments
  label.control-label= t('helpers.documents')
  | &nbsp
  = f.simple_fields_for :organization_attachments, wrapper: :table_form do |attachment|
    - unless attachment.object.file_stored?
      .file-input
        = attachment.input :file, as: :file, wrapper: :vertical_file_input, label: false
    - if attachment.object.file_stored?
      = link_to attachment.object.file.name, attachment.object.file.url, target: '_blank', class: 'file-name'    
    = attachment.input :description, as: :string, input_html: {class: "file-description", placeholder: t('activerecord.attributes.organization_attachment.description')}    
    = attachment.link_to_remove class: 'file-destroy btn btn-danger'
      span aria-hidden="true"
        i.fa.fa-trash
  = f.link_to_add t('helpers.add_file'), :organization_attachments, class: 'btn btn-default'

app/views/admin/organizations/_form.slim
= simple_nested_form_for [:admin, @resource], wrapper_mappings: { boolean: :vertical_boolean}, 
html: {class: "form-horizontal localized-form"} do |f|
  .form-inputs
    == render 'admin/helpers/locale_selectors'
    = error_explanation(@resource)
    = f.input :name, as: :localized_string
    = f.input :logo, as: :image
    = f.association :activity_types, input_html: {class: 'select2-input'}
    = f.input :chief_name, as: :localized_string
    = f.input :competence, as: :localized_imperavi
    = f.input :capabilities, as: :localized_imperavi
    = f.input :offers, as: :localized_imperavi
    = f.input :interests, as: :localized_imperavi
    = f.input :contacts, as: :localized_imperavi
    = f.input :address, as: :localized_imperavi
    = f.input :website
    = f.input :coordinates_geojson, input_html: {class: "map-selector", data: {draw: [:marker]}}
    = f.input :in_slider
    == render "admin/shared/gallery", f: f
    == render "attachments", f: f
    
  .form-group
    = link_to "Отменить", admin_organizations_path, class: 'btn btn-default'
    | &nbsp
    = f.button :submit
    | &nbsp
    = submit_and_continue f

app/views/admin/organizations/_list.slim
- if @collection.blank?
  = t('helpers.not_found')
- else
  table.table.table-hover.table-bordered
    thead
      tr
        th Название
        th
    tbody.rowlink data-link="row"
      - @collection.each do |resource| 
        tr
          td.object-ref
            - if can? :update, resource
              = link_to url_for([:edit, :admin, resource]) do
                .td-inner-container
                  = resource.name
            - else
              .td-inner-container
                = resource.name
          td.unstoppable
            - if can? :destroy, resource
              = link_to url_for([:admin, resource]), class: 'btn-remove', method: :delete, data: { confirm: "Вы уверены?" } do
                .fa.fa-trash
== paginate @collection

app/views/admin/organizations/index.slim
.row.page-title
  .col-lg-12
    h1 = t('views.admin.organizations.index.title')
.row.top-actions
  .col-lg-6
    = form_tag nil, class: 'input-group', method: :get do
        = text_field_tag :query, nil, value: params[:query], placeholder: t('helpers.search_placeholder'), class: 'input form-control'
        span.input-group-btn
          = submit_tag t('helpers.search'), class: 'button btn btn-lg btn-primary'
  .col-lg-6
    - if can? :create, Organization
      = link_to new_admin_organization_path, class: 'btn btn-success btn-lg pull-right' do
        i.fa.fa-plus
        | &nbsp
        = t('helpers.buttons.add')
.row
  .col-lg-12
    == render 'list'